### ISSUE TITLE
[STYLE] Landing email buttons on mobile

### ISSUE THREAD

**Issue by Brayan-724** [github-20k/super-star#10]
### Styling change

The buttons to subscribe aren't responsive. There are sharp border instead of a curve. It is simple, also add a few margin.
![Screenshot_20230507_212357](https://user-images.githubusercontent.com/70247585/236733874-d2d929c2-eb5b-435c-aea9-ac7f16d7413b.jpg)

**Comment by nevo-david** [comment]
I fixed it, Thank you!

**Comment by nevo-david** [comment]
closing it
