### ISSUE TITLE
Replace ngrok with tunnelmole

### ISSUE THREAD

**Issue by robbie-cahill** [github-20k/super-star#11]
### Description

To generate public URLs for local development, Super-Star uses the unofficial [ngrok](https://www.npmjs.com/package/ngrok) dependency from `npm`. This dependency has a few issues:
- As noted in the [README](https://github.com/bubenshchykov/ngrok/blob/master/README.md) for [ngrok](https://www.npmjs.com/package/ngrok), its simply a wrapper around the `ngrok` CLI tool. So, you must download and install the `ngrok` CLI tool as an external dependency and this complicates setup
- You need to manually match the version of the [ngrok](https://www.npmjs.com/package/ngrok) dependency to specific versions of the ngrok CLI client, further complicating setup. For example, using the version 5 of the `npm` dependency is not supported with version 2 of the CLI client. 
- The `npm` dependency is maintained by a third party and is not officially supported by ngrok. So, ngrok could make some unexpected change and the integration might break suddenly.
- The `ngrok` CLI tool is not FOSS and is closed source. For some projects, this could create licensing issues if the maintainers are not ok with that for whatever reason.

I propose replacing `ngrok` with [tunnelmole](https://www.npmjs.com/package/ngrok). Tunnelmole is open source and the runtime is implemented in pure JavaScript.

You only need to add it as an `npm` dependency and you don't need to install anything separately. `npm` automatically manages all dependencies, you don't need to manually match up versions of anything.

As the runtime code is pure JavaScript, it is automatically cross platform and will run on all operating systems and CPU architectures that NodeJS can run on.

To compare usage:
`ngrok`
First, download and install `ngrok` from [ngrok.com](https://ngrok.com), or this won't work. Also, ensure your version of the `ngrok` CLI tool is compatible with the version of the `ngrok` NPM dependency you are using.
```js
const url = await ngrok.connect(3000);
```

`tunnelmole`
```js
const url = await tunnelmole({ port: 3000 });
```
This works right away, without installing anything separately. I had a look through your project and I think it should be fairly straightforward to refactor your code to use `tunnelmole`.

Let me know if you'd like to move ahead and I'll create a PR with the changes.

**Comment by nevo-david** [comment]
Hi @robbie-cahill!
Thank you for that.
Do you think you can make it generic to be able to choose between them?
For me ngrok works great with the paid version.

**Comment by robbie-cahill** [comment]
Yep I've made a PR: https://github.com/github-20k/super-star/pull/12

ngrok should work as normal, it will be controlled by environment variables (`NGROK_ACTIVE` / `TUNNELMOLE_ACTIVE`).
